name: "Min Htaw Lon"
  on: 
    pull_request:
      branches:
        -dev

  jobs:
    build:
      name: "Build Docker Images"
      runs-on: ubuntu-latest
      steps: 
        - name: Setup PHP with tools
            uses: shivammathur/setup-php@v2
            with:
              php-version: '8.3'
        - name: "Testing step"
          run: |
          echo "Hello Wrold"