name: Laravel CI

on:
  pull_request:
    branches:
      - dev

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0

      - name: Generate application key
        run: php artisan key:generate

      - name: Run tests
        run: php artisan test
